#### Declare two matrices as n dimensional arrays

In [1]:
import numpy as np

a = np.array([[4, 3], [2, 1]])
b = np.array([[1, 2], [3, 4]])
print("a is \n" + str(a))
print("b is \n" + str(b))


a is 
[[4 3]
 [2 1]]
b is 
[[1 2]
 [3 4]]


#### Addition

In [2]:
print(a+b)

[[5 5]
 [5 5]]


#### Multiplication

In [3]:
print(a@b)
print("\n Another way is \n")
print(np.matmul(a,b))

[[13 20]
 [ 5  8]]

 Another way is 

[[13 20]
 [ 5  8]]


#### Matrix elementwise multplication (Hadamard product) is

In [4]:
print(a*b)

[[4 6]
 [6 4]]


#### Transpose  $$a^{T}$$

In [5]:
print(a)
print(np.transpose(a))

[[4 3]
 [2 1]]
[[4 2]
 [3 1]]


#### Inverse (uses linalg)     $$a^{-1}$$

In [6]:
print(np.linalg.inv(a))

[[-0.5  1.5]
 [ 1.  -2. ]]


In [7]:
print("determinant of a is " + str(np.linalg.det(a)) )
print("determinant of b is " + str(np.linalg.det(b)) )
print("condition number of a is " + str(np.linalg.cond(a)))
print("condition number of b is " + str(np.linalg.cond(b)))

determinant of a is -2.0
determinant of b is -2.0000000000000004
condition number of a is 14.933034373659252
condition number of b is 14.933034373659265


The above shows ill conditioned matrices (condition number much higher than 1).
Highly sensitive to small changes in input - bad for solving.


In [8]:
np.linalg.solve(a,b)

array([[ 4.,  5.],
       [-5., -6.]])

In [9]:
print("a is \n")
print(a)
aa = np.array([[5, 3], [2, 1]])
print("\n aa is \n")
print(aa)

a is 

[[4 3]
 [2 1]]

 aa is 

[[5 3]
 [2 1]]


In [10]:
print("Small change in input leads to much larger change in output while solving.")
print(np.linalg.solve(aa,b))

Small change in input leads to much larger change in output while solving.
[[  8.  10.]
 [-13. -16.]]


In [11]:
print("eigen values of a: \n" + str(np.linalg.eig(a)[0]) + \
     "\n and eigenvector of a: \n" + str(np.linalg.eig(a)[1]))

eigen values of a: 
[ 5.37228132 -0.37228132]
 and eigenvector of a: 
[[ 0.90937671 -0.56576746]
 [ 0.41597356  0.82456484]]


#### Singular Value Decomposition

In [12]:
(U,S,v) = np.linalg.svd(a)
print("Eigen values estimated from SVD are: ")
print(S)

Eigen values estimated from SVD are: 
[5.4649857  0.36596619]


U and transpose of v from SVD are each estimated orthogional matrices $$ U . U^{T} \approxeq I$$

In [13]:
print(U@np.transpose(U))

[[ 1.00000000e+00 -9.73614252e-17]
 [-9.73614252e-17  1.00000000e+00]]


In [14]:
print(v@np.transpose(v))

[[ 1.00000000e+00 -1.72088383e-17]
 [-1.72088383e-17  1.00000000e+00]]


U and v are analogous to rotation and S is analogous to stretching of the matrix.
SVD is a closed-form solution which can be used for dimension reduction by choosing the top eigenvalues.

Estimating the original matrix a back from SVD estimates

In [15]:
print(U@np.diag(S)@v)

[[4. 3.]
 [2. 1.]]


Note that we used np.diag(S) and not S

In [16]:
np.diag(S)

array([[5.4649857 , 0.        ],
       [0.        , 0.36596619]])

Algorithmic complexity of SVD remains high. So, in higher dimensions it is still not easy to compute: $$O(mn^2+m^2n)$$

Machine Learning methods such as gradient descent may be used to estimate in high dimensions.

But there can be the curse of dimensionality (sparsity and meaningless distance) in high dimensional estimations.